parameters:

    #
    # Factories
    #
    elcodi.core.attribute.factory.attribute.class: Elcodi\Component\Attribute\Factory\AttributeFactory
    elcodi.core.attribute.factory.attribute_value.class: Elcodi\Component\Attribute\Factory\ValueFactory
