services:

    #
    # Factories
    #

    #
    # Factory for Attribute entities
    #
    elcodi.factory.attribute:
        class: %elcodi.factory.attribute.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.attribute.entity.attribute.class%"]]

    #
    # Factory for Value entities
    #
    elcodi.factory.attribute_value:
        class: %elcodi.factory.attribute_value.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.attribute.entity.attribute_value.class%"]]
