services:

    #
    # Object Managers
    #
    elcodi.object_manager.attribute:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.attribute.entity.attribute.class% ]

    elcodi.object_manager.attribute_value:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.attribute.entity.attribute_value.class% ]
